[tool.towncrier]
name = "try-manage-releases"
version = ""
filename = "CHANGELOG.rst"
directory = "changelogs"
issue_format = "`#{issue} <https://example.com/i/{issue}>`__"

[[tool.towncrier.type]]
directory = "feature"
name = "Features"
showcontent = true

[[tool.towncrier.type]]
directory = "model"
name = "Migration"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bugfixes"
showcontent = true
